// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package second

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Customer struct {
	ID       pgtype.UUID `json:"id"`
	Forename string      `json:"forename"`
	Surname  string      `json:"surname"`
	Dob      pgtype.Date `json:"dob"`
	Male     pgtype.Bool `json:"male"`
}
