---
logger:
  level: debug
secrets:
  openbao:
    scheme: http
    host: localhost
    port: 8200
data:
  relational:
    - host: localhost
      port: 5432
      user: tester
      database: test_data
      sslmode: disable
      secret: dev-postgres-test
